export const currencyList = [
  {
    currency: 'BRL',
    symbol: 'R$',
    country: 'Brazil',
    locale: 'pt-BR',
    name: 'Brazilian Real',
    isoCode: 'BR',
  },
  {
    currency: 'USD',
    symbol: '$',
    country: 'United States',
    locale: 'en-US',
    name: 'US Dollar',
    isoCode: 'US',
  },
  {
    currency: 'EUR',
    symbol: '€',
    country: 'European Union',
    locale: 'de-DE',
    name: 'Euro',
    isoCode: 'EU',
  },
  {
    currency: 'JPY',
    symbol: '¥',
    country: 'Japan',
    locale: 'ja-JP',
    name: 'Japanese Yen',
    isoCode: 'JP',
  },
  {
    currency: 'GBP',
    symbol: '£',
    country: 'United Kingdom',
    locale: 'en-GB',
    name: 'British Pound Sterling',
    isoCode: 'GB',
  },
  {
    currency: 'CHF',
    symbol: 'CHF',
    country: 'Switzerland',
    locale: 'de-CH',
    name: 'Swiss Franc',
    isoCode: 'CH',
  },
  {
    currency: 'AUD',
    symbol: 'A$',
    country: 'Australia',
    locale: 'en-AU',
    name: 'Australian Dollar',
    isoCode: 'AU',
  },
  {
    currency: 'CAD',
    symbol: 'C$',
    country: 'Canada',
    locale: 'en-CA',
    name: 'Canadian Dollar',
    isoCode: 'CA',
  },
  {
    currency: 'HKD',
    symbol: 'HK$',
    country: 'Hong Kong',
    locale: 'zh-HK',
    name: 'Hong Kong Dollar',
    isoCode: 'HK',
  },
  {
    currency: 'NZD',
    symbol: 'NZ$',
    country: 'New Zealand',
    locale: 'en-NZ',
    name: 'New Zealand Dollar',
    isoCode: 'NZ',
  },
  {
    currency: 'CNY',
    symbol: '¥',
    country: 'China',
    locale: 'zh-CN',
    name: 'Chinese Yuan',
    isoCode: 'CN',
  },
  {
    currency: 'SEK',
    symbol: 'kr',
    country: 'Sweden',
    locale: 'sv-SE',
    name: 'Swedish Krona',
    isoCode: 'SE',
  },
  {
    currency: 'NOK',
    symbol: 'kr',
    country: 'Norway',
    locale: 'nb-NO',
    name: 'Norwegian Krone',
    isoCode: 'NO',
  },
  {
    currency: 'DKK',
    symbol: 'kr',
    country: 'Denmark',
    locale: 'da-DK',
    name: 'Danish Krone',
    isoCode: 'DK',
  },
  {
    currency: 'INR',
    symbol: '₹',
    country: 'India',
    locale: 'hi-IN',
    name: 'Indian Rupee',
    isoCode: 'IN',
  },
  {
    currency: 'RUB',
    symbol: '₽',
    country: 'Russia',
    locale: 'ru-RU',
    name: 'Russian Ruble',
    isoCode: 'RU',
  },
 
  {
    currency: 'ZAR',
    symbol: 'R',
    country: 'South Africa',
    locale: 'en-ZA',
    name: 'South African Rand',
    isoCode: 'ZA',
  },
  {
    currency: 'MXN',
    symbol: '$',
    country: 'Mexico',
    locale: 'es-MX',
    name: 'Mexican Peso',
    isoCode: 'MX',
  },
  {
    currency: 'THB',
    symbol: '฿',
    country: 'Thailand',
    locale: 'th-TH',
    name: 'Thai Baht',
    isoCode: 'TH',
  },
  {
    currency: 'KRW',
    symbol: '₩',
    country: 'South Korea',
    locale: 'ko-KR',
    name: 'South Korean Won',
    isoCode: 'KR',
  },
];
